server.port=8082
spring.application.name=TheHindustanLive
spring.main.allow-bean-definition-overriding=true

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://hindustanlive:S5vDSSihgdcFAUz2@cluster0.irsd6.mongodb.net/hindu_live?retryWrites=true&w=majority

# Redis Configuration
spring.data.redis.host=red-cum5cddumphs738d22i0
# spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=  # Leave empty if Redis doesn't require a password
spring.data.redis.timeout=15m

# Redis Cache Configuration
spring.cache.type=redis
spring.cache.redis.time-to-live=15m
spring.cache.redis.cache-null-values=true
spring.cache.redis.use-key-prefix=true
spring.cache.redis.key-prefix=redisCache

# Redisson Configuration (Optional)
redisson.singleServerConfig.address=redis://red-cum5cddumphs738d22i0:6379
# redisson.singleServerConfig.address=redis://localhost:6379
redisson.singleServerConfig.password=""
redisson.threads=2
redisson.nettyThreads=2
