server.port=8082
spring.application.name=TheHindustanLive
spring.main.allow-bean-definition-overriding=true
# spring.data.mongodb.uri=mongodb+srv://hindustanlive:s5vdssihgdcfauz2@cluster0.irsd6.mongodb.net/hindu_live
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.data.mongodb.uri=mongodb+srv://hindustanlive:S5vDSSihgdcFAUz2@cluster0.irsd6.mongodb.net/hindu_live?retryWrites=true&w=majority